version: "3"
services:
  ddd-db:
    container_name: ddd-db
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "ddd_sample"
  campaign-service:
    container_name: campaign-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      DB_HOST: ddd-db
      DB_USERNAME: root
      DB_PASSWORD: 1234
      WAIT_HOSTS: ddd-db:3306
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60
    command: bash -c "/wait && flask run"
