##########################
## Linters & Formatting ##
##########################

[tool.flake8]
max-line-length = 120
min_python_version = "3.10"
exclude = ["env", ".venv", "venv"]
max-complexity = 6
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
extend-ignore = ["E203"]

[tool.mypy]
python_version = 3.10
exclude = ["env"]
plugins = "sqlmypy"

implicit_optional = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
warn_unused_ignores = true
warn_unreachable = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "tests/*"
disallow_untyped_decorators = false
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "sqlalchemy.orm.decl_api"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sqlalchemy_utils.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mypy-sendgrid.*"
ignore_missing_imports = true

[tool.isort]
profile = "black"
py_version = 310
extend_skip = ["env", ".venv", "venv"]

#############
## Testing ##
#############

[tool.pytest.ini_options]
minversion = "7.0.1"
testpaths = [
    "tests",
]
